### ISSUE TITLE
Preview Doesn't Return data

### ISSUE THREAD

**Issue by AdvocisCA** [Beee4life/acf-city-selector#112]
[New Recording - 9/19/2022, 3:28:58 PM](https://vimeo.com/751375360/b98d814967)

**Comment by AdvocisCA** [comment]
[debug.zip](https://github.com/Beee4life/acf-city-selector/files/9601870/debug.zip)

**Comment by Beee4life** [comment]
I can confirm that nothing shows in the csv contents, when you click preview. I hadn't noticed that, but that is not related to any front-end issues there might be.

This 'preview' is admin only view and is completely separate.

Will look into it.

**Comment by Beee4life** [comment]
I have found the fix, but if you don't want to wait 'till it's released, you can easily change it your self.

Change line 64 in `admin/acfcs-preview.php` from 
```
echo acfcs_render_preview_results();
```
to
```
echo acfcs_render_preview_results( $csv_info[ 'data' ] );
```

New release will be coming in the next 48 hours.

**Comment by AdvocisCA** [comment]
Perfect! Thanks 😊
