### ISSUE TITLE
meta query search/filter

### ISSUE THREAD

**Issue by alfinnasution** [Beee4life/acf-city-selector#117]
Thanks for the great plugin.

I have a question and probably will be handy too in the future for others. Are we able to use meta query when we search/filter using wp_query? I was thinking it'd be similar like ACF group_field, but it's not working for me, maybe you can point out the right direction.

    'meta_query'    => array(
        array(
            'key'       => 'field_name_countryCode',
            'compare'   => '=',
            'value'     => 'AU',
        )
    )

**Comment by Beee4life** [comment]
I think this will do the trick.

```
'meta_query'     => [
	[
		'key'     => "field_name",
		'value'   => '"AU"', // notice the quotes
		'compare' => 'LIKE',
	],
],
```

**Comment by Beee4life** [comment]
What you can also do is create custom values for it. It only takes a small piece of code to arrange this.

Find that [here](https://acf-city-selector.com/faq/store-city-selector-values-as-single-meta/).

**Comment by Beee4life** [comment]
A new version has been released, with the option to save as a single value. That should solve your issue.
