### ISSUE TITLE
Search&Filter

### ISSUE THREAD

**Issue by lolobomac** [Beee4life/acf-city-selector#118]
Hello, 
Is possible use acf city selector with search&filter pro plugin? I cant see the acf city selector field in this plugin. 
Thanks!

**Comment by Beee4life** [comment]
I don't know, I never tried.

But I'm sure that if you follow [these instructions](https://acf-city-selector.com/faq/store-city-selector-values-as-single-meta/), you can use it because I think the plugin works easier/better with single meta values.

**Comment by Beee4life** [comment]
I just released a new version which includes an option to save meta as single value.
