### ISSUE TITLE
Small field select2 

### ISSUE THREAD

**Issue by jlb-1985** [Beee4life/acf-city-selector#124]
Hi,

First, thanks for creating this plugin! It’s great! 
I have a small issue. When I choose Select2 in acf, I get very small fields when I’m making a post and want to select a state or city. It makes it hard to see and choose any of them. 

![1AA862E7-4467-4B89-866B-F6B6CB562595](https://user-images.githubusercontent.com/130216366/230713935-ddd1882a-4b55-40f7-af1d-b176434d577a.jpeg)

**Comment by jlb-1985** [comment]
![FA844278-3AFF-4E17-A061-CFC63286F6E9](https://user-images.githubusercontent.com/130216366/230714087-017bb045-83ec-41b3-b532-744828f35540.jpeg)

**Comment by Beee4life** [comment]
Canit be you created different tabs/groups in your acf fields ?

**Comment by Beee4life** [comment]
I think it's caused, if the field is not immediately into 'focus'. I think it also happens, when you put it on a tabbed page, which is not visible yet when you load the page.

I think it can be fixed by setting the width to 100%.

**Comment by jlb-1985** [comment]
I found out what caused it, it was very simple. If I disable show label then the width turned normal.

**Comment by Beee4life** [comment]
Good you found a way to make it work, but it's not optimal plugin behaviour. Should always be 100%
