### ISSUE TITLE
add new city not work

### ISSUE THREAD

**Issue by exolon82** [Beee4life/acf-city-selector#127]
Hi, i dont found the tutorial for add new city in the file csv ITA, because, when i use this example Amsterdam;NH;Noord-Holland;NL;Netherlands , not work, even if the program tells me that it has added a new city, when I go to look in the select, the city does not appear

**Comment by Beee4life** [comment]
I don't know by heart what the delimiter is, but if the delimiter in the csv is `,` and you use `;` then it won't work, they need to be the same.

**Comment by exolon82** [comment]
I modified the Italy file that I also paid for, a little while ago, I modified it in the sense that I added a line of the missing village, then I imported it with the delimiter` ;` but not work not show in the field select

**Comment by exolon82** [comment]
when import the file, show this words,  `You have successfully imported 3831 cities from "test it.csv".`

**Comment by exolon82** [comment]
[test it.csv](https://github.com/Beee4life/acf-city-selector/files/14530711/test.it.csv)
this is the file, the my row add is mesagne

**Comment by exolon82** [comment]
![image](https://github.com/Beee4life/acf-city-selector/assets/16225287/0e15251b-adb4-4535-98f4-2484bb92b0ef)
i have used this file, and i  have only add one row for try .. but not show the new row add from me, in the preview you can see my line, but in the select you can't see it, and I also tried to clear the cache

**Comment by exolon82** [comment]
ok, the file is correct i have tried the file in the new site staging, there must be a cache problem, yet I tried deleting everywhere. what is missing!?!

**Comment by Beee4life** [comment]
have you tried clearing the transients ?

**Comment by exolon82** [comment]
> have you tried clearing the transients ?

yes

**Comment by Beee4life** [comment]
can you make a screenshot of the part of the csv where you added a new city ?

**Comment by exolon82** [comment]
![image](https://github.com/Beee4life/acf-city-selector/assets/16225287/9525692b-b688-43c1-aa78-7e1ce1b3fb29)
![image](https://github.com/Beee4life/acf-city-selector/assets/16225287/11cdf7a9-b13c-47c1-a403-bb355460b860)
but not show in the select
![image](https://github.com/Beee4life/acf-city-selector/assets/16225287/0d0e3d35-de75-4d1e-8902-7eef8be9e50f)
![image](https://github.com/Beee4life/acf-city-selector/assets/16225287/631149ba-cf40-475f-9a1a-a3bcd02f4c4a)

**Comment by exolon82** [comment]
It's really strange,

**Comment by exolon82** [comment]
ok solved, i have used, a plugin for flush transient,

**Comment by exolon82** [comment]
your flush transient does not work

**Comment by Beee4life** [comment]
> your flush transient does not work

ah, good to know, i will look into it. 

You didn't need a plugin to clear all transients . You can use [wp-cli](https://developer.wordpress.org/cli/commands/transient/delete/) or an SQL query, like below.

```
DELETE FROM wp_options WHERE option_name LIKE ('%\_transient\_%')
```

**Comment by exolon82** [comment]
what is the name of database for this plugin?

**Comment by exolon82** [comment]
i have this problem in this moment https://www.awesomescreenshot.com/video/25774014?key=faee0ac193a381a9b6fed95ae0758d6f

**Comment by exolon82** [comment]
and if try to delete transient, show this message A critical error has occurred on your website. Check your site administrator's inbox for instructions. https://www.awesomescreenshot.com/video/25774198?key=72a62035dc3b57e265c52bb1bab8c788

**Comment by exolon82** [comment]
ok sorry, i have solved, the problem was is php version

**Comment by Beee4life** [comment]
Phjew :) glad to hear, I already thought I needed to do some debugging.
