### ISSUE TITLE
Issue with ACF City Selector Plugin - Deprecated Property Creation

### ISSUE THREAD

**Issue by vincent11235** [Beee4life/acf-city-selector#138]
Hi [Beee4life](https://github.com/Beee4life),

I hope this message finds you well. 
I recently encountered an issue with my website's ACF City Selector plugin. 
The ACF form has stopped functioning, and I noticed the following error messages via WP Debugging:

Deprecated: Creation of dynamic property ACF_City_Selector::$settings is deprecated in /home/mywebsite/public_html/wp-content/plugins/acf-city-selector/ACF_City_Selector.php on line 35

Deprecated: Creation of dynamic property ACF_City_Selector::$l10n is deprecated in /home/mywebsite/public_html/wp-content/plugins/acf-city-selector/ACF_City_Selector.php on line 81

Attached are the screenshots for your reference:

<img width="544" alt="image" src="https://github.com/user-attachments/assets/2c5dfeb3-f6b6-43c8-8c09-fe70769b302b">

<img width="487" alt="image" src="https://github.com/user-attachments/assets/7b5ac63a-c75d-43e5-a31b-b7a0dd134c32">

I suspect these deprecations are causing the issue. Could you please guide me on how to address these deprecations in the city selector to restore functionality?

Thank you for your assistance.

**Comment by Beee4life** [comment]
Hey, I hadn't seen your message yet, but this has been solved in the meanwhile in the latest 2 versions.

**Comment by vincent11235** [comment]
Hi [Beee4life](https://github.com/Beee4life),

Thank you for your response. 
I decided to create a taxonomy for the nation and city selector. 
Thanks for your help!

**Comment by Beee4life** [comment]
I don't see how a taxonomy is related to the issue you started this thread with.

Also i didn't build the plugin to serve taxonomies, so not really relevant here imo.
