### ISSUE TITLE
The same plugin with Make, Model and Year of Vehicles

### ISSUE THREAD

**Issue by mystinfoweb** [Beee4life/acf-city-selector#14]
That would be a great alternative and I saw many users asking how to do it in the forums, and your plugin can do it, usto changing the values I believe?

**Comment by Beee4life** [comment]
Can you post some links so I can see what others are asking ?

**Comment by mystinfoweb** [comment]
https://support.advancedcustomfields.com/forums/topic/chained-taxonomy-select/
https://support.advancedcustomfields.com/forums/topic/select-parent-tax-term-then-child/
https://support.advancedcustomfields.com/forums/topic/multi-level-selects/

I do not have all the links I visualized, I searched a lot, until I found the topic where you posted this plugin looking for Country, State and City, because the logic is the same.

**Comment by Beee4life** [comment]
Well, we're talking about 2 different things here. 
As far as I understand, you want to list taxonomies, then another taxonomy and then another taxonomy which contains a post in that taxonomy.

This plugin is meant for a meta value, which is a different approach I think.

Maybe it is possible but I don't have the time to look into it. We're still developing this plugin.
V0.1 just went live and we have plenty to do before we officially get to 1.0.

Maybe you can do something yourself with custom coding but it doesn't have my interest yet to incorporate something.

Good luck.
