### ISSUE TITLE
Javascript error when used on a User Form, Register page on Register Page

### ISSUE THREAD

**Issue by etiennejcharles** [Beee4life/acf-city-selector#15]
Thank you for the AMAZING work on the plugin!

When I add the city selector with those settings. 

<img width="1022" alt="setting example" src="https://user-images.githubusercontent.com/2872476/33896353-9a87fa8a-df30-11e7-9fda-a0fc84b153e1.png">

Then go to: `[sitename]wp-login.php?action=register` 

And try to select a city, I get the following error in the dev tools console: 
`Uncaught ReferenceError: ajaxurl is not defined`

<img width="1454" alt="error" src="https://user-images.githubusercontent.com/2872476/33895921-93d18a5e-df2f-11e7-943f-df715040831c.png">

I found that the ajax url is added only on the `wp_head` hook. 

<img width="696" alt="ajax-url" src="https://user-images.githubusercontent.com/2872476/33896042-d92c203c-df2f-11e7-9a6b-e3a17b76708c.png">

The hook called for the registration page is called `login_head`.

By adding 
`add_action( 'login_head', 'city_selector_ajaxurl' );`
Right below line 13, triggers the login_head, and ads to ajax and fixes the problem. 

Did you want me to PR? 

Let me know

**Comment by Beee4life** [comment]
not sure if it's hooked to login_head if it then loads on the rest of the site... maybe adding another action for login_head would be a better solution... I haven't tested this option yet on a register form, so I can't tell for sure...

Did you test it yourself with login_head ? And if so did it work when you use it in an acf-form ? because that is the reason it was added to the front side.

**Comment by etiennejcharles** [comment]
**Did you test it yourself with login_head ?**
-> I tested it with "login_head" and it worked ;) 

**And if so did it work when you use it in an acf-form**
-> I'm not sure how I would go and do that ~ ... (my reasons for using it was only on a registration form so the ), by ACF form we do mean [this](https://www.advancedcustomfields.com/resources/acf_form/)?

**Comment by Beee4life** [comment]
Yes that is the ACF form I mean. It was built because I needed it in there. Didn't test with registration. TBH I didn't even know this was an option :)

**Comment by etiennejcharles** [comment]
Well that is interresting! ~ In that case for any futur reference my idea was in my `functions.php` to add the following: 

```php
function my_own_ajax_url() {
?>
    <script type="text/javascript">
        var ajaxurl = "<?php echo admin_url( 'admin-ajax.php' ); ?>";
   </script>
<?php
}
add_action( 'login_head', 'city_selector_ajaxurl' );
```

In order not the hack the plugins code, if the intention was to use it in an ACF Form, maybe it would be an overkill to make a PR for that.

**Comment by olbweb** [comment]
I've been hunting around and noticed the following:

1. When updating a Post, the posts.php file includes the following lines that contains the selected Country/State/City that are all shown on the Post edit screen:
925  <option value="BE">Belgium</option>
926	<option value="LU" selected="selected">Luxembourg</option>
927  <option value="NL">Netherlands</option>
2777   var city_selector_vars = {"countryCode":"LU","stateCode":"LU-na","cityName":"Wiltz"};

2. When updating a User profile, the useredit.php only includes the first 3 lines, but not the fourth. 
738   <option value="BE" selected="selected">Belgium</option>
739   <option value="LU">Luxembourg</option>
740   <option value="NL">Netherlands</option>
This means that the selected Country name is shown on the User edit screen, but the State and City are NOT shown.

**Comment by olbweb** [comment]
Sorry, my last comment didn't display properly so I will try again:

**Comment by olbweb** [comment]
Sorry, my previous comment didn't display properly, so I'll try again.

I've been hunting around and noticed the following:

1    When updating a Post, the posts.php file includes the following lines that contain the selected Country/State/City that are all shown on the Post edit screen:
925  option value="BE">Belgium</option
926  option value="LU" selected="selected">Luxembourg</option>
927  option value="NL">Netherlands</option
2777  var city_selector_vars = {"countryCode":"LU","stateCode":"LU-na","cityName":"Wiltz"}; */

2 When updating a User profile, the useredit.php only includes the first 3 lines, but not the fourth.
738  option value="BE" selected="selected">Belgium</option
739  option value="LU">Luxembourg</option
740  option value="NL">Netherlands</option
This means that the selected Country name is shown on the User edit screen, but the State and City are NOT shown.
