### ISSUE TITLE
ACF City Selector Csv

### ISSUE THREAD

**Issue by Webinnovations1** [Beee4life/acf-city-selector#19]
Hello! Thanks for great plugin. I checked your demo version here http://acfcs.berryplasman.com/see-it-in-action/ and it looks really good. Could you help me, please? I need the cities and states for US, but i can't find a great csv file with all data. I noticed in demo, that you have the US states/cities. Could you send me the csv file, please?
Also could you explain how to show this 3 fields on the front-end as on your demo? I'd be really greatful for your reply! Thanks.

**Comment by Beee4life** [comment]
Yes I do have them (somewhere ;) ) and they will be placed online so you can buy them as well, but I can't promise yet, when this will be. The plugin is not 100% yet, because it can't be placed in a repeater (yet) so wanted to focus on the core plugin before making the countries available.

**Comment by Webinnovations1** [comment]
Ok, but can i use it as on your demo now? I would like to show states/cities i one form. Could you explain how can i do that on front-end?
Also how much will this plugin cost? I need this decision as soon as possible. Can i buy seperately the csv of US states/cities?

**Comment by Beee4life** [comment]
The plugin is and remains free... but soon you will be able to buy separate country packages, which consist of all states/cities for that country. For the US we have all states and just over 20000 cities.

I can't promise when I can give you this because I'm going on holiday tomorrow... It depends solely on available time...

**Comment by Webinnovations1** [comment]
Ok, understood. But could you help me, please? It's really important and i will be grateful for your advice. How can i show these 3 fields http://prntscr.com/k5nmpf on the front-end ?

**Comment by Beee4life** [comment]
First you need to look into how you can [add a form to the front-end](https://www.advancedcustomfields.com/resources/create-a-front-end-form/). That is an ACF function. Just read the ACF docs for that. You don't need my help for that.

Then install my plugin and add the field to the form.

As I said, I am on holiday tomorrow. I can't help you now. All info that is needed is available in the support docs. Reg. any new countries, has to wait (at least) until I get back from holiday. Sorry...

**Comment by Webinnovations1** [comment]
Ok. I appreciate your help! Have a nice holiday! Thanks.

**Comment by Beee4life** [comment]
I will try to look into it soon after my holiday, but I didn't think people would be interested before the plugin is 100% ready, so that's why I didn't make haste with this...

**Comment by Beee4life** [comment]
Did you manage to include the form ?
