### ISSUE TITLE
how to list all states in a country and cities

### ISSUE THREAD

**Issue by jallescaetano** [Beee4life/acf-city-selector#20]
Hello, Congratulations for the plugin you did.

I am trying to use get_field_object () to get all the
States and cities, to create a filter in the frontend, could you help me?

Here is an example of how I'm trying to do it.

Thank you

$field_key = "field_5b4df093b4581";
$field = get_field_object($field_key);

if( $field )
{
	echo '<select name="' . $field['key'] . '">';
		foreach( $field['choices'] as $k => $v )
		{
			echo '<option value="' . $k . '">' . $v . '</option>';
		}
	echo '</select>';
}

**Comment by Beee4life** [comment]
Can you provide a bit more info what you want to do because I don't think this is the way to go.

For one, there is no array key choices in the field object. It returns the field + its values, if used on a singular post/page (since you didn't provide a post id).

**Comment by Beee4life** [comment]
Closing it due to lack of feedback.
