### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by gelaxe** [Beee4life/acf-city-selector#22]
Hi! Could you add fields in admin panel for select necessary countries list or wp filter in populate_country_select and other? This will be enough to support localization via wpml for example.

**Comment by Beee4life** [comment]
Sorry, I don't understand the question. Can you please elaborate ?

**Comment by gelaxe** [comment]
I need to separate different writing of cities and countries names on different language. Span - España for example. For multilanguage sites Im using WPML. He has ACF support.

**Comment by Beee4life** [comment]
The site I wrote this plugin for also uses WPML but I haven't looked into i18n for the cities yet. Still developing it...

**Comment by Beee4life** [comment]
I have internationalised all cities/states/countries which come with the plugin but I don't think that is what you meant, is it ?

**Comment by Beee4life** [comment]
@gelaxe did you see my reply ?

**Comment by Beee4life** [comment]
Closing due to no follow-up.
