### ISSUE TITLE
Using acf-city-selector with Search and Filter Pro

### ISSUE THREAD

**Issue by olbweb** [Beee4life/acf-city-selector#23]
I have a custom post type called 'Venues'.

I created an ACF Field Group for this custom post type, and 'acf-city-selector' is one of the fields in this group.

It works beautifully on:
1. My front-end-form. It worked straight 'out of the box' with Hookturn's 'Advanced Forms Pro' plugin which I highly recommend for use with the acf-city-selector add-on (the only foms plugin I could find that worked).
2. The backend post edit screen.
3. My Beaver Themer singular post layout for this custom post type (after adding the code in the documentation to my functions.php file and using a shortcode in my posts layout).

But now I want to use it in a filter so site users can filter the posts to their own location. I have it working in Search and Filter Pro BUT it doesn't provide the 3 droptdowns for Country, State and City but rolls them all into a single dropdown showing codes but not names. This is not useable.

So I'd appreciate some advice on a search plugin that will work with City-Selector or some PHP code that will enable it to display properly in my filter.

Thanks

**Comment by Beee4life** [comment]
Can you be more specific ? Every value can be isolated to be used.

**Comment by olbweb** [comment]
In Search and Filter Pro, when building the UI, I have added a Post Meta Field and selected 'country-region-city' from the available options. The output looks like this: 
![acf-cs_-n_s-and-f-pro](https://user-images.githubusercontent.com/45557191/49420075-e49b0d80-f7dd-11e8-8111-ece0d661e9ba.JPG)
I need it to show like this:
![acf-cs_-n_s-and-f-pro_2](https://user-images.githubusercontent.com/45557191/49420236-95a1a800-f7de-11e8-8773-f00640a5a8c8.JPG)
Can you help with this?

p.s. I'm not a developer. I can't write php code, although I can understand it to some extent and have  successfully added and modified PHP code provided by some plugin developers, including the output snippet on your documentation page.

**Comment by Beee4life** [comment]
My plugin doesn't fill your dropdown so if you want to use it you have to add the plugin as a new field, so the new fields will appear in your form.

**Comment by olbweb** [comment]
Sorry, I don't understand this. 

I have already created the ACF 'city_selector' custom field and it is working perfectly on my front-end form, in my posts and on my singular posts layout.

I now want to put a filter on a post grid (archive layout) so a site user can filter the posts by country/region/city.  I thought I would be able to use search and filter Pro to do this but it isn't working (as shown in my last comment), probably because it isn't a standard ACF field type.  So I need to know how to use it as a filter.

**Comment by olbweb** [comment]
Hi,

Thanks for your replies to my comments.

I probably haven't explained this very well, so I'll try again.

1. In my website (under contruction), I created a custom post type called 'venues', then added a small number of test posts. Each test post was asigned a country, region and city using ACFCS,  in either NL, BE or LU.
2. I then built a search form using 'Search and Filter Pro" with 3 search fields. The third field is my ACFCS field called 'country-region-city'
3. I then added this search form to my archive post layout for 'venues', so that the posts can be filtered.
4 The filter works perfectly. The dropdown shown on my comment above (4th December) is 100% correct. It shows the locations that have been assigned to my posts. The counts are also correct.
5. The only problem is the way it displays which is not user friendly because:
    a) it shows country and region codes, not names.
    b) It should show countries first. Then, when the user selects a country it should show the regions.         Then, when the user selects a region it should show the cities.

I need a solution for this problem (probably some php code that I can add my functions.php or to the archive template).

Thanks

**Comment by Beee4life** [comment]
I built this plugin for a certain (private) purpose, namely the option to select location data in a front-end form. That works, so I reached my goal. After that I decided to make it more usable for every one but I can't find the time yet. 

In reply to your point 4: 
a) yes correct, because names are spelled differently in different languages, so hence why country/region code are stored. Those don't change in a different language.

b) the plugin is meant for ACF, not for Search & Filter. I did not build this plugin with the idea to accommodate other plugins. Maybe in the future, but not right now.

As the readme explains, the data is stored in an array (like checkboxes), so you can never just simply echo that value. You need to retrieve that array and then split it up in 3 parts.

It is fairly easy to create your own search form without the search filter plugin though.
![screenshot 2018-12-07 at 09 59 02](https://user-images.githubusercontent.com/4508731/49637836-cf54f780-fa06-11e8-96e4-ca9de858d361.png)

I want to try and look into improving the plugin during the holidays but no promises yet.

**Comment by olbweb** [comment]
Thanks

**Comment by Beee4life** [comment]
If you're interested, I'm willing to help you build a custom form think because I think that's an easier fix for you than to adapt my plugin (right now) to your situation. 

If interested, let me know.

**Comment by Beee4life** [comment]
This is the code for steps 1, 2 and 3.
```
function add_location_search_values( $post_id ) {

    $city_selector_field   = 'field_58441dcb5c20f';
    $city_search_field     = 'field_584c67a239f35';
    $state_search_field    = 'field_584c77690114b';
    $country_search_field  = 'field_584c779a0114c';

    // if location field is set
    if ( isset( $_POST[ 'acf' ][ $city_selector_field ] ) ) {

        $stored_location = get_field( $field_name, $post_id );
        $city_selector   = $_POST[ 'acf' ][ $city_selector_field ];
        $search_country  = $city_selector[ 'countryCode' ];
        $search_state    = substr( $city_selector[ 'stateCode' ], 3 );
        $search_city     = esc_html( $city_selector[ 'cityName' ] );

        // always update search values
        update_field( $country_search_field, $search_country, $post_id );
        update_field( $state_search_field, $search_state, $post_id );
        update_field( $city_search_field, $search_city, $post_id );
    }
}
add_action( 'acf/save_post', 'add_location_search_values', 20 );
```

What you could also do is load all countries and cities (for example through a transient) and then loop through that array.

If the above doesn't cut it and you need help with a transient, let me know.

**Comment by olbweb** [comment]
Thanks for providing this code Beee-4life, and on Christmas Day of all days!
It looks perfect and I'lll have a go at it tomorrow.

**Comment by olbweb** [comment]
Hi Beee,

I've tried it but need a little more assistance to get it working.

Here is how I tested it:
1. Copied the code into my functions.php file and added my 4 field-keys as shown below.
2. Selected one post in the backend (the custom post type is 'venues') and manually entered the search country, state and city to match the city-selector values.
3. Updated then refreshed the post.
4. Changed the city name in the city_selector dropdown.
5. Updated then refreshed the post.
6. The city_search_field had not been updated. 

So, at the moment it isn't working.

In my ACF field group, the 3 new fields are all 'Text' fields with a Character Limits of 30 and I have added their key values into your code, as follows:
    $city_selector_field   = 'field_5bd2edbc9ae1f';  //  field name 'country-region-city'
    $city_search_field     = 'field_5c24bfc67de5c';  //  field name 'venue_search_country'
    $state_search_field    = 'field_5c24bff47de5d';  // field name 'venue_search_region'
    $country_search_field  = 'field_5c24c02b7de5e';  // field name 'venue_search_city'

I also changed 'countryCode' and 'stateCode' to 'countryName' and 'stateName' because I want to update the field names, not the codes, as follows:
    $stored_location = get_field( $field_name, $post_id );
    $city_selector   = $_POST[ 'acf' ][ $city_selector_field ];
    $search_country  = $city_selector[ 'countryName' ];
    $search_state    = substr( $city_selector[ 'stateName' ], 3 );
    $search_city     = esc_html( $city_selector[ 'cityName' ] );
I don't know what the 3 is for in the $ search_state' line. Should I delete it?

Are there any other variables that I need to change? For example, where you have 'acf' in 3 places.

Thanks,
CP

**Comment by Beee4life** [comment]
If you want to list the state name, the substring function is not needed. [Substr](http://php.net/manual/en/function.substr.php) strips the first 3 characters from the string. So in for example NL-NH (Netherlands, North Holland), you would get NH.

ACF is needed in the $_POST otherwise you would have to use `get_field` to retrieve the (stored) value. Now it's provided in $_POST['acf'].

I don't know why it's not working for you. Works like a charm here. You need to find out if that function is actually 'being hit'.

What if you add a die('DIE') or an error_log('HIT') in your function, does it get 'hit' after saving ?

Btw, the line below is not needed. The variable `$stored_location` is not used anywhere. Never saw it was useless, until now. But that's not related to the issue at hand.

```
$stored_location = get_field( $field_name, $post_id );
```

**Comment by olbweb** [comment]
Both. 
Subscribers will add venues using a front-end form and I will check and publish their posts in the back-end. I might also add/edit venues in the back-end.

**Comment by olbweb** [comment]
I've removed the Substr function and the '$stored_location = get_field( $field_name, $post_id );' line.
It still isn't working.

In the di_postmeta table, the meta_value in the 'country-region-city' field is truncated to this a:3:{s:11:"countryCode";s:2:"NL";s:9:"stateCode";s...
Could this be something to do with it?

In any case, I agree that it looks like the function isn't being hit. So how do I add the 'die' and 'error-log'?

**Comment by olbweb** [comment]
I installed an error log plugin and when I updated a 'venue' (post). it reported as follows:

"Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'add_location_search_values' not found or invalid function name in /home/curren91/public_html/discoveriffic.com/wp-includes/class-wp-hook.php on line 286"

Note that the message refers to our new function. Here is the code as it currently is:

<?php 
/*
 * Here is the code to extract Country, Region and City from the city-selector field
 * and post them to 3 individual custom fields for post type 'Venues'
 */

function add_location_search_values_venues( $post_id ) {

    $city_selector_field   = 'field_5bd2edbc9ae1f';
    $city_search_field     = 'field_5c24bfc67de5c';
    $state_search_field    = 'field_5c24bff47de5d';
    $country_search_field  = 'field_5c24c02b7de5e';
 
	// if location field is set
    if ( isset( $_POST[ 'acf' ][ $city_selector_field ] ) ) {

        $city_selector   = $_POST[ 'acf' ][ $city_selector_field ];
        $search_country  = $city_selector[ 'countryName' ];
        $search_state    = $city_selector[ 'stateName' ];
        $search_city     = esc_html( $city_selector[ 'cityName' ] );

        // always update search values
        update_field( $country_search_field, $search_country, $post_id );
        update_field( $state_search_field, $search_state, $post_id );
        update_field( $city_search_field, $search_city, $post_id );
    }
}
add_action( 'acf/save_post', 'add_location_search_values', 20 );
 ?>


Here is the section of 'class-wp-hook.php' with line 286 indicated:

	/**
	 * Calls the callback functions added to a filter hook.
	 *
	 * @since 4.7.0
	 *
	 * @param mixed $value The value to filter.
	 * @param array $args  Arguments to pass to callbacks.
	 * @return mixed The filtered value after all hooked functions are applied to it.
	 */
	public function apply_filters( $value, $args ) {
		if ( ! $this->callbacks ) {
			return $value;
		}

		$nesting_level = $this->nesting_level++;

		$this->iterations[ $nesting_level ] = array_keys( $this->callbacks );
		$num_args = count( $args );

		do {
			$this->current_priority[ $nesting_level ] = $priority = current( $this->iterations[ $nesting_level ] );

			foreach ( $this->callbacks[ $priority ] as $the_ ) {
				if( ! $this->doing_action ) {
					$args[ 0 ] = $value;
				}

				// Avoid the array_slice if possible.
				if ( $the_['accepted_args'] == 0 ) {
					$value = call_user_func_array( $the_['function'], array() );
				} elseif ( $the_['accepted_args'] >= $num_args ) {
LINE 286				$value = call_user_func_array( $the_['function'], $args );
				} else {
					$value = call_user_func_array( $the_['function'], array_slice( $args, 0, (int)$the_['accepted_args'] ) );
				}
			}
		} while ( false !== next( $this->iterations[ $nesting_level ] ) );

		unset( $this->iterations[ $nesting_level ] );
		unset( $this->current_priority[ $nesting_level ] );

		$this->nesting_level--;

		return $value;
	}

**Comment by olbweb** [comment]
... something went wrong above. It is missing the function code so here it is:

/*
 * Here is the code to extract Country, Region and City from the city-selector field
 * and post them to 3 individual custom fields for post type 'Venues'
 */

function add_location_search_values_venues( $post_id ) {

    $city_selector_field   = 'field_5bd2edbc9ae1f';
    $city_search_field     = 'field_5c24bfc67de5c';
    $state_search_field    = 'field_5c24bff47de5d';
    $country_search_field  = 'field_5c24c02b7de5e';
 
	// if location field is set
    if ( isset( $_POST[ 'acf' ][ $city_selector_field ] ) ) {

        $city_selector   = $_POST[ 'acf' ][ $city_selector_field ];
        $search_country  = $city_selector[ 'countryName' ];
        $search_state    = $city_selector[ 'stateName' ];
        $search_city     = esc_html( $city_selector[ 'cityName' ] );

        // always update search values
        update_field( $country_search_field, $search_country, $post_id );
        update_field( $state_search_field, $search_state, $post_id );
        update_field( $city_search_field, $search_city, $post_id );
    }
}
add_action( 'acf/save_post', 'add_location_search_values', 20 );

**Comment by Beee4life** [comment]
If you're sing the front-end form, you need to input the post_id manually. I do that too... here is my complete function (I trimmed it down for clarity).

```
function add_location_search_values( $post_id ) {

    if ( false == $post_id ) {
        $post_id = $_GET[ 'id' ]; // because I edit a form with &id
    }

    $post_type = get_post_type( $post_id );

    if ( PostTypes::PROFILE == $post_type ) {
        $city_selector_field   = 'field_58441dcb5c20f';
        $city_search_field     = 'field_584c67a239f35';
        $state_search_field    = 'field_584c77690114b';
        $country_search_field  = 'field_584c779a0114c';
    } elseif ( PostTypes::COMPANY == $post_type ) {
        $city_selector_field   = 'field_5938c49eb706a';
        $country_search_field  = 'field_59399c3822167';
        $state_search_field    = 'field_59399c7022169';
        $city_search_field     = 'field_59399c6e22168';
    } else {
        $city_search_field     = false;
        $city_selector_field   = false;
        $country_search_field  = false;
        $state_search_field    = false;
    }

    // if location field is set
    if ( isset( $_POST[ 'acf' ][ $city_selector_field ] ) ) {

        $city_selector   = $_POST[ 'acf' ][ $city_selector_field ];
        $search_country  = $city_selector[ 'countryCode' ];
        $search_state    = substr( $city_selector[ 'stateCode' ], 3 );
        $search_city     = esc_html( $city_selector[ 'cityName' ] );

        // always update search values
        update_field( $country_search_field, $search_country, $post_id );
        update_field( $state_search_field, $search_state, $post_id );
        update_field( $city_search_field, $search_city, $post_id );
    }
}
add_action( 'acf/save_post', 'add_location_search_values', 20 );
```

It seems that when you get the error of "undefined function", you're not calling the function with add_action correctly.

Removing `$stored_location = get_field( $field_name, $post_id );` won't fix it, it does nothing.

An error plugin is not necessary. Just add `error_log('Something');` and make sure WP_DEBUG_LOG is set to true in wp-config.php.

Then check /wp-content/debug.log for the results.

Your function seems ok, can't see anything wrong right now...

**Comment by olbweb** [comment]
I fixed the function name in the  ‘add_action’ line to be the same as the actual function name (I had made a mistake). 
That got cityName to update properly but not stateName or countryName

I then changed back to countryCode and stateCode (using your code) and it worked perfectly. 

Unfortunately I need ‘countryName’ and ‘stateName’, so please do me another favour and provide the correct code for these 2 lines:
       $search_country  = $city_selector[ 'countryName' ];
        $search_state    =  $city_selector[ 'stateName' ];

After that is working, I will add the code you provided for the front-end form.
Regarding that code:
a)	What do you mean by ‘you need to input the post_id manually’?
b)	Where do I find the post_id ?
c)	Where do I input it?

I think we are nearly there. Finally!
Thanks

**Comment by olbweb** [comment]
After some trial and error, I have finally managed to resolve the code to get countryName and stateName. 

It is working perfectly but please review just to make sure it is OK.

/*
* Here is the code to extract Country, Region and City names from the city-selector field
* and post them to 3 individual custom fields for post type 'Venues'
*/
function add_venue_search_values( $post_id ) {
    $country_search_field = 'field_5c24bfc67de5c';
    $state_search_field   = 'field_5c24bff47de5d';
    $city_search_field    = 'field_5c24c02b7de5e';

    {
    $city_selector 	   = get_field('country-region-city');
    $search_country  = esc_html( $city_selector[ 'countryName' ] );
    $search_state       = esc_html( $city_selector[ 'stateName' ] );
    $search_city         = esc_html( $city_selector[ 'cityName' ] );

    // always update search values
    update_field( $country_search_field, $search_country, $post_id );
    update_field( $state_search_field, $search_state, $post_id );
    update_field( $city_search_field, $search_city, $post_id ); 
    }
}
add_action( 'acf/save_post', 'add_venue_search_values', 20 );

**Comment by olbweb** [comment]
I just realised that I don't need the code for the front-end form because:

1. All venue posts submitted using the front-end form are posted with a status of 'pending-review'
2. All posts therefore need to be checked and published in the back-end
3. When the 'Publish' button in the back-end is clicked, it will activate the back-end function that updates the 3 search fields.

I will keep the code you sent in case I need it one day (probably will).

Thankyou so much for your help and I will make a donation as soon as my site is earning.

**Comment by Beee4life** [comment]
Glad to see you figured it out.... Don't hesitate to ask if you need more help.
