### ISSUE TITLE
Attaching city-selector to users

### ISSUE THREAD

**Issue by olbweb** [Beee4life/acf-city-selector#24]
I have a similar issue to #15.

When I attach a city_selector field to a user, it appears to be working properly as follows:
1. On the user profile screen in the backend, the city, state and country can be selected and display perfectly.
2. When the user profile is saved, the city-selector field in the usermeta table is updated properly.

Unfortunately the State and City fields are no longer rendered on the user profile screen. These fields are empty despite the fact that the selections are correctly stored in the usermeta table. If anything else is changed in the user profile, it is necessary to re-enter these fields in order to save the changes. This requires first selecting another country, state, city, then re-entering the original country, state and city.

I have no idea how to fix this. I tried adding the code shown in issue #15 to my functions.php but it made no difference.

Thanks in advance for any advice/assistance with this issue.

**Comment by Beee4life** [comment]
I have never attached it to a user so I can't speak from experience.

What does your console give for messages ?

**Comment by olbweb** [comment]
There are no error messages.

Here is the user profile page after I selected country, state and city. Shown before I updated the user profile:
![image](https://user-images.githubusercontent.com/45557191/50730551-d73dbe00-11a3-11e9-9071-3dee9abdc167.png)
This is correct.


Here is the record in usermeta after updating the user profile:
![image](https://user-images.githubusercontent.com/45557191/50730448-05ba9980-11a2-11e9-94d4-d3b85a28b0df.png)
This is correct.


Here is the back-end after updating the user profile:
![image](https://user-images.githubusercontent.com/45557191/50730458-3bf81900-11a2-11e9-913f-759153c9ab35.png)
The State and City aren't showing and can't be selected without changing the Country, then changing it back again.


Here is the code I copied from #15 and have tried to customise for my site.. I'm not sure if it is the same problem but, if it is, my code doesn't look correct (my coding skills aren't strong):
![image](https://user-images.githubusercontent.com/45557191/50730507-0d2e7280-11a3-11e9-925f-17ee60477abf.png)

**Comment by Beee4life** [comment]
What does the console provide for info ?

**Comment by Beee4life** [comment]
The variable `$user_id` is not needed, since it's not used in the function.

**Comment by olbweb** [comment]
I've been hunting around and noticed the following:

1 When updating a Post, the posts.php file includes the following lines that contain the selected Country/State/City that are all shown on the Post edit screen:
925  option value="BE">Belgium</option
926  option value="LU" selected="selected">Luxembourg</option
927  option value="NL">Netherlands</option
2777  var city_selector_vars = {"countryCode":"LU","stateCode":"LU-na","cityName":"Wiltz"}; 

2 When updating a User profile, the useredit.php only includes the first 3 lines, but not the fourth.
738  option value="BE" selected="selected">Belgium</option
739  option value="LU">Luxembourg</option
740  option value="NL">Netherlands</option
This means that the selected Country name is shown on the User edit screen, but the State and City are NOT shown.

**Comment by Beee4life** [comment]
Could be but I would have to do some hunting do be sure... Can't tell right now, nor do I have the time to look into this right now. Sorry. Will be a while....

**Comment by olbweb** [comment]
No worries. I’ll just have to wait a while (hopefully not too long).

Much appreciated!

**Comment by olbweb** [comment]
Hi again Beee4life,

Have you had a chance to look into this yet?

Thanks,

Chris P

 

From: olbweb@optusnet.com.au <olbweb@optusnet.com.au> 
Sent: Monday, January 7, 2019 8:22 PM
To: 'Beee4life/acf-city-selector' <reply@reply.github.com>
Subject: RE: [Beee4life/acf-city-selector] Attaching city-selector to users (#24)

 

No worries. I’ll just have to wait a while (hopefully not too long).

Much appreciated!

**Comment by Beee4life** [comment]
Nope and won't have time for it before mid april (at the earliest)...

**Comment by olbweb** [comment]
Realistically, will you get around to this? 

 

I like your plugin a lot but If you really can’t help, I might have to stop using it and look for an alternative.

 

If you can help (mid-to-late April at the latest), I will appreciate it greatly.

 

Cheers,

Chris Parker

**Comment by Beee4life** [comment]
I can't and won't promise that... I have built this plugin to accommodate my website, which is to be able to select a location in a post.

I never intended to use it for a user... I focus purely on my own project and if I have time then I might get around to it... but again; zero promises...

**Comment by olbweb** [comment]
Ok.




Get Outlook for Android







On Mon, Mar 25, 2019 at 11:21 PM +1100, "Beee" <notifications@github.com> wrote:












I can't and won't promise that... I have built this plugin to accommodate my website, which is to be able to select a location in a post.


I never intended to use it for a user... I focus purely on my own project and if I have time then I might get around to it... but again; zero promises...

**Comment by akgoenka** [comment]
Hi

I have solved what you are looking for. Please replace this file in your fields folder and it will work like charm for Users now

Cheers!
Ashish[
[acf-city_selector-v5.php.zip](https://github.com/Beee4life/acf-city-selector/files/3640274/acf-city_selector-v5.php.zip)

](url)

**Comment by Beee4life** [comment]
Can you please add the code here instead of a zip ?

**Comment by hardweb-it** [comment]
Same issue for me.

Thanks to @akgoenka for your zip share.

@Beee4life by comparing the files, there are some edits, here is the code which replace the original one, from line 167 to 211.

`				if ( isset( $_GET['action'] ) && $_GET['action'] === 'edit' || isset( $_GET['id'] ) || isset( $_GET['user_id'] ) ) {

			    					
					if ( isset( $_GET['id'] ) ) {
						$post_id = $_GET['id'];
					}elseif ( isset( $_GET['user_id'] ) ) {
						$user_id = $_GET['user_id'];
					}
					 else {
						$post_id = get_the_ID();
					}
				//	echo "<script>console.log('USer ID: " .  $post_id . "' );</script>";
					if ( isset( $_GET['user_id'] ) ) {
						$fields     = get_field_objects( 'user_' . $user_id );
						}
						else {
							$fields     = get_field_objects( $post_id );
						}
//						echo "<script>console.log('Debug Objects: " .  $fields . "' );</script>";
					$field_name = 'acf_city_selector';
					if ( is_array( $fields ) && count( $fields ) > 0 ) {
						foreach( $fields as $field ) {
							if ( isset( $field['type' ] ) && $field['type'] == 'acf_city_selector' ) {
								$field_name = $field['name'];
								break;
							}
						}
					}
					if ( isset( $_GET['user_id'] ) ) {
						$post_meta = get_user_meta( $user_id, $field_name, 1 );
					}
					else {
						$post_meta = get_post_meta( $post_id, $field_name, 1 );
					}

					if ( ! empty( $post_meta['cityName'] ) ) {
						wp_localize_script( 'acf-city-selector-js', 'city_selector_vars', array(
							'countryCode' => $post_meta['countryCode'],
							'stateCode'   => $post_meta['stateCode'],
							'cityName'    => $post_meta['cityName'],
						) );
					}
                    
				}
				if ( current_user_can('edit_user',get_current_user_id()) ) {
					$user_id = get_current_user_id();
					$fields     = get_field_objects( 'user_' . $user_id );
					$field_name = 'acf_city_selector';
					if ( is_array( $fields ) && count( $fields ) > 0 ) {
						foreach( $fields as $field ) {
							if ( isset( $field['type' ] ) && $field['type'] == 'acf_city_selector' ) {
								$field_name = $field['name'];
								break;
							}
						}
					}
						$post_meta = get_user_meta( $user_id, $field_name, 1 );
						if ( ! empty( $post_meta['cityName'] ) ) {
							wp_localize_script( 'acf-city-selector-js', 'city_selector_vars', array(
								'countryCode' => $post_meta['countryCode'],
								'stateCode'   => $post_meta['stateCode'],
								'cityName'    => $post_meta['cityName'],
							) );
						}
				}
			}`

**Comment by Beee4life** [comment]
I will try to look into this in the coming weeks... can't promise when, due to deadlines

**Comment by Beee4life** [comment]
Took a bit to look at this... The solution looks fairly straight forward and apart from the commented lines, it seems good.

I'm about to release a new version. This request won't be in there yet, but I'll try to squeeze it in the next version.

**Comment by hardweb-it** [comment]
@Beee4life There's also a deprecated "contextual_help" function, which appear on backend from WP 5.3.x
Take a look on this for the new version. 😉

**Comment by Beee4life** [comment]
already fixed in next version

**Comment by Beee4life** [comment]
@akgoenka i looked into your code a bit more... it looks good, but I'm wondering why you localize it twice.... See https://pastebin.com/k2UeB6rX on lines 43 and 66.

**Comment by Beee4life** [comment]
@olbweb @akgoenka @hardweb-it I just released v0.10 which includes support for user profiles. I think I made it all work.

Will close this topic for now. If any new issues come up, please open a new issue.
