### ISSUE TITLE
Display on front

### ISSUE THREAD

**Issue by kev-sq** [Beee4life/acf-city-selector#25]
Hello and thanks for this plugin.

I've installed it and it works on backoffice very well.

However I would like to display it on front page in a search form.
I've seen that you make it here : http://acfcs.berryplasman.com/see-it-in-action/

Can you help me how to do this ?

Thanks in advance.

Regards,

Kévin

**Comment by Beee4life** [comment]
That is not something from my plugin, but from ACF itself.

Find the info on [this page](https://www.advancedcustomfields.com/resources/create-a-front-end-form/).

**Comment by kev-sq** [comment]
Sorry if I misspoke.

My question was not how to create a form, but how to display the selectors on a page of my site?

**Comment by Beee4life** [comment]
You have to create a front-end form :) 
AFAIK there's no other way

**Comment by kev-sq** [comment]
Hum ok, I'll check that ! 
Thanks for your quick answers !

**Comment by Beee4life** [comment]
[This](https://www.advancedcustomfields.com/resources/acf_form/) is a better starting point.
