### ISSUE TITLE
changes all provinces, cities while I'm changing country in repeater

### ISSUE THREAD

**Issue by hamzahabib2000** [Beee4life/acf-city-selector#30]
Hello Dear,
I'm using this in a Repeater, and it made changes to all fields while I change only 1 country field ....

**Comment by Beee4life** [comment]
That is correct. That is also mentioned in the disclaimer, see [here](https://github.com/Beee4life/acf-city-selector#disclaimer).

I have a few things I would like to fix, this is one of them. It now gets a 'hardcoded' ID, which I need to make dynamic.

**Comment by hamzahabib2000** [comment]
I've made corrections, plz guide me how can I merge this ...

**Comment by Beee4life** [comment]
Create a merge request and I'll  look at it.

**Comment by hamzahabib2000** [comment]
![image](https://user-images.githubusercontent.com/12470901/74604182-337c4c80-50dd-11ea-8286-11c52f4b946a.png)

 Choose different branches or forks above to discuss and review changes. 
thanks for the patience ... I'm getting option disabled...

**Comment by Beee4life** [comment]
I don't know what you mean ?
You compare master to master, there are no diffs.

**Comment by hamzahabib2000** [comment]
![image](https://user-images.githubusercontent.com/12470901/74604433-cb7b3580-50df-11ea-91dd-0bed01a0f4e6.png)
I also tried to upload files directly, but it is disabled ... 
and I'm also new to github .... need guide for merging requests ...

**Comment by Beee4life** [comment]
Please google how to do this, if [this link](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) won't suffice.

**Comment by hamzahabib2000** [comment]
okay, thanks ...

**Comment by Beee4life** [comment]
PS I would recommend looking into and using [Sourcetree](https://www.sourcetreeapp.com/) so you dont' have to do manual uploads and so.

**Comment by Beee4life** [comment]
I am releasing a beta release tomorrow with repeaters/groups. If you're interested you're welcome to test.

**Comment by hamzahabib2000** [comment]
Many thanks for Invitation .... I will try ...

**Comment by Beee4life** [comment]
The branch 'repeaters' is the one which will be released. Should be good to go I think.

**Comment by Beee4life** [comment]
FYI: It's fixed for repeater and now also groups. Test it yourself in the branch named `promise`.

I will create a beta release for it today/tomorrow.
