### ISSUE TITLE
Can't edit using acf_form. 

### ISSUE THREAD

**Issue by dlpcmiles28** [Beee4life/acf-city-selector#31]
It's not showing the correct saved data, just blank

**Comment by Beee4life** [comment]
Can you be a bit more specific ? Maybe share some code ?

**Comment by dlpcmiles28** [comment]
Have you tried editing some values using acf_form? I used acf_form to do a
front end editing and the acf selector isn't displaying the current data.
It displays the country but the state and city is blank.

**Comment by lanceadam** [comment]
Sounds like you haven't imported any data yet?

**Comment by Beee4life** [comment]
It works fine for me... @dlpcmiles28

**Comment by Beee4life** [comment]
Closing it due to no follow-up from OP.
