### ISSUE TITLE
Warning: The length of the state abbreviation on line 1 is incorrect.

### ISSUE THREAD

**Issue by lanceadam** [Beee4life/acf-city-selector#33]
I'm trying to import city, state & country data and I get the following error. I am importing global data, and Australia use a 3 digit state abbreviation. How can I fix this?

**Comment by Beee4life** [comment]
The plugin is tailored to 2 digit state abbreviation, according to the international standard (not sure if I use the correct terminology).

**Comment by lanceadam** [comment]
Thanks for the reply, please check here: https://en.m.wikipedia.org/wiki/ISO_3166-2

Specifically this text:

The first part is the ISO 3166-1 alpha-2 code of the country;

<strong>The second part is a string of up to three alphanumeric characters</strong>, which is usually obtained from national sources and stems from coding systems already in use in the country concerned, but may also be developed by the ISO itself.

**Comment by lanceadam** [comment]
ISO standard stipulation the regional/state code can be made up of 3 characters. Surely it is an easy enough fix to allow 3 characters to make this plugin internationally supported to standards.

**Comment by lanceadam** [comment]
Here are two examples of the ISO 3166-2 where there is a two digit country code, followed by a 3 digit region/state code:

https://en.m.wikipedia.org/wiki/States_and_territories_of_Australia
https://en.m.wikipedia.org/wiki/ISO_3166-2:GB

**Comment by Beee4life** [comment]
Well, it's built for 2 chars for state length, so that's why stuff goes wrong...
I will add it to my todo list, but no promises on eta.
Have several things I wanna try and implement

**Comment by Beee4life** [comment]
FYI: I'm planning to release a new version this weekend, which i had been working on for a while (see pull requests). I will not incorporate your request yet, but I will promise to add it to the version after.

**Comment by Beee4life** [comment]
@lanceadam if you're from AUS you might be able to help me out. Working on the next version with 3 char for states and I'm creating a csv for Australia, but missing a handful of states for some cities.

Maybe you can fill in the blanks.

**Comment by Beee4life** [comment]
The latest version allows for a 3 character state abbreviation.

Since that was the original question, closing this topic.

**Comment by lanceadam** [comment]
@Beee4life I'm happy to help, where can I find the file and missing states?

**Comment by Beee4life** [comment]
Will make them available somewhere in the next few days.
