### ISSUE TITLE
SQL query in Import file is wrong

### ISSUE THREAD

**Issue by lanceadam** [Beee4life/acf-city-selector#34]
In the import excel file, the query is:

`="INSERT INTO "&README!$D$15&"cities ( city_name_ascii, state_code, states, country_code, country )"`

But the table structure is:

![image](https://user-images.githubusercontent.com/1610130/78325151-8ee99780-75c2-11ea-8cb3-d7a4f531aa81.png)

**Comment by lanceadam** [comment]
**city_name_ascii** should change to : **city_name**
**states** should change to : **state_name**

**Comment by Beee4life** [comment]
The excel can be outdated. haven't worked on the plugin in a while, but hoping to pick it up soon again.

**Comment by Beee4life** [comment]
I will change this in the next version.

**Comment by Beee4life** [comment]
This should be changed in the new version I released shorty ago...
