### ISSUE TITLE
City value can't remain in AC field's form

### ISSUE THREAD

**Issue by assoscoupa** [Beee4life/acf-city-selector#52]
Hello,

When someone selects Country, State and City, after the update, the value of the city does not remain in the form. The mentioned price simply does not appear in the form and in addition to this, there is no city to choose from. 

If he chooses another state then he sees the corresponding cities. After that if someone selects the previous state then the cities of the first state return available for selection.

watch this video below:
https://www.youtube.com/watch?v=yDT_p0GtDK8

**Comment by Beee4life** [comment]
Hi.... thanks for the info...

I see you have added your own cities for Greece. First thought that comes to mind is something to do with the character encoding, since I've never experienced anything like this yet.

Can you please retest the same situation but with one of the default provided countries ?

**Comment by assoscoupa** [comment]
I find this problem too. In wp-admin/options-general.php?page=acfcs-search
I receive this message when I push a "Search" button.

Warning: uasort() expects parameter 1 to be array, null given in ......../wp-content/plugins/acf-city-selector-master/inc/acfcs-search.php on line 121

Warning: count(): Parameter must be an array or an object that implements Countable in .../wp-content/plugins/acf-city-selector-master/inc/acfcs-search.php on line 122

See that:
https://drive.google.com/file/d/1z1qAMgNyrDUH6ESiCJGkj1j8d3YaSfmd/view?usp=sharing

**Comment by assoscoupa** [comment]
I tried in my installation the add-on with the cities of **Belgium** and it works normally in the choice data in the post and in the search. 

I check my data (for Greek Mynicipality) and i find all UTF-8.

**Comment by Beee4life** [comment]
I think that confirms my suspicion regarding the character encoding but have to test to be sure.

I had the same issue with a customer with another plugin. I found that using [Sublime](https://www.sublimetext.com/) text editor (free) to open the csv and then save it as UTF-8 did the trick in 99% of the cases.

I code in PhpStorm but sublime is easier for quick access/editing single files (imo).

I probably won't have time until this weekend to look into it. Just spend my week of holiday coding on another plugin ([B3 Onboarding](https://github.com/Beee4life/b3-onboarding/tree/next-version)) I am about to release a major update for, if you're interested.

**Comment by Beee4life** [comment]
> I find this problem too. In wp-admin/options-general.php?page=acfcs-search
> I receive this message when I push a "Search" button.
> 
> Warning: uasort() expects parameter 1 to be array, null given in ......../wp-content/plugins/acf-city-selector-master/inc/acfcs-search.php on line 121
> 
> Warning: count(): Parameter must be an array or an object that implements Countable in .../wp-content/plugins/acf-city-selector-master/inc/acfcs-search.php on line 122
> 
> See that:
> https://drive.google.com/file/d/1z1qAMgNyrDUH6ESiCJGkj1j8d3YaSfmd/view?usp=sharing

Got it, noted.

Did you use any search parameters or did you just click search ?

I think this can be fixed (temporarily) when you add
`$city_array = [];`

on the line before
`foreach( $cities as $city_object ) {`

It seems there are no results because it looks like $city_array is not defined. Looks like I forgot to add a default because $city_array doesn't exist when no results.

Btw you can also add images here, just drag and drop 'em in, that's it :)

**Comment by assoscoupa** [comment]
I also tried with the sublime to make sure the data is utf-8 but in the end the select form 
 problem didn't work.


-----
The search problem was partially solved after I added the code you sent.

When I click find without selecting or adding anything else it brings me all the cities of Greece but when I select a state it does not bring me the cities that belong to it.

------

Thank you for your time. I will use your add-on with this little bug. Take your time. I understand that you have various issues like all of us.

Ps. Thank for advice about images.

**Comment by Beee4life** [comment]
> I also tried with the sublime to make sure the data is utf-8 but in the end the select form
> problem didn't work.
> 
> The search problem was partially solved after I added the code you sent.
> 
> When I click find without selecting or adding anything else it brings me all the cities of Greece but when I select a state it does not bring me the cities that belong to it.
> 
> Thank you for your time. I will use your add-on with this little bug. Take your time. I understand that you have various issues like all of us.
> 
> Ps. Thank for advice about images.

I'll try to look into your csv this weekend. Regarding the empty array, I will add that to a hotfix or else a next version. I see you're subscribed so you'll get notified.

**Comment by assoscoupa** [comment]
Hello Beee.

I used the new release (0.22.1), but my problems remained.

Ι Tried this: I Replaced "state_code" in my csv, from greek characters to latin and my problems seem to have been resolved!!!

If you have the mood and time, try to modify the code so that the state_code field accepts characters other than Latin, such as Greek.

Anyway, thank you for your help.

**Comment by Beee4life** [comment]
This was a hotfix for the undefined index you mentioned, nothing else...

**Comment by Beee4life** [comment]
@assoscoupa does it still occur with the latest version ?

**Comment by hardweb-it** [comment]
@Beee4life I found an issue on your lastest 1.3.1 version of plugin.

If the City name contain apex (or apostrophe), it won't "saved" properly.
For example:

-  "City name" is saved properly.
-  "City's name" won't saved.

Debugging a bit: in database the value of City appear stored as serialized array without any escape char before the apex.

I opened the "acfcs-functions.php" and edit the lines 536, 543 and 550 with:

`$selected_value = esc_attr($stored_value);`

Now the City with apex will appear properly as selected on the dropdown.
That's strange, by echoing $key and $selected_value, they appears as equal string, but at line 572 the ternary condition doesn't work as expected.

I'm no pretty sure about this method could be the best, maybe you need to check or escape the chars before store values.
I have not much time to investigate better, but take a look and check yourself.

Thanks.

**Comment by Beee4life** [comment]
@hardweb-it Please make a new issue out of it, so assocoupa's topics is not diluted with your issue. Thanks.

**Comment by hardweb-it** [comment]
@Beee4life done.

**Comment by Beee4life** [comment]
@assoscoupa I'm closing this topic due to no follow-up.
