### ISSUE TITLE
Plugin Not Activating after installation

### ISSUE THREAD

**Issue by krazysage** [Beee4life/acf-city-selector#55]
Tried to activate the plugin and it doesn't Activate . Timeout Error. 

![image](https://user-images.githubusercontent.com/6060951/87851678-aa31a600-c918-11ea-9757-032f797baf4c.png)

Attaching the error , looking forward to working with this.

**Comment by Beee4life** [comment]
Hi, i'm sorry, you experienced. I have never experienced anything like it.
It looks like the database is doing some action which times out.

Some questions:
* Do you have ACF installed and activated ?
* Did you test with all other plugins (except ACF) deactivated ?
* Did you try with a default WP theme ?
* Did you add any custom cities yourself maybe which could be really big ?

**Comment by duanearnett** [comment]
Seeing a similar issue. Manually creating the prefix_cities table and everything works fine. I do not get the timeout, but the table is just never created, the plugin activates successfully, then just never saves data, but does not throw an error. 

```
What ? | Value
-- | --
Operating system | Apache
PHP version | 7.2.24-0ubuntu0.18.04.6
Server IP | ****
Server port | 8080
Scheme | http
Home path | /var/www/html


What ? | Value
-- | --
WordPress version | 5.5
Home URL | http://wordpress.local:8080
Admin email | *****
Blog public | 0
Users can register | 0
Page on front | 0
Current theme | ****
Template folder | ***
Charset | UTF-8
Text direction | LTR
Language | en-US


Name | Version
-- | --
ACF City Selector | 0.22.2
Advanced Custom Fields PRO | 5.9.1
Custom Post Type UI | 1.8.0
```

**Comment by Beee4life** [comment]
This might have to do with the port.... but not sure. I might be that somewhere a current url function is used, which does not include the port number (yet) afaik. I also came across this in another plugin of mine. If not added, it will be added in next version.

**Comment by Beee4life** [comment]
Closing due to no feedback provided.
