### ISSUE TITLE
Ability to save country only

### ISSUE THREAD

**Issue by Akots** [Beee4life/acf-city-selector#56]
We have cases on the project where user needs just select a country.
Currently if select a country, do not select a city and then click save, country is not saving.

Also in case if just to show country field only and save it is not saving results.

WordPress 5.4.2
ACF PRO 5.8.9

**Comment by Beee4life** [comment]
That is correct. It's called a City selector, not a Country selector.
A country selector is nothing more than a static list of countries. 
You can create that yourself easily in 5 minutes.

**Comment by Akots** [comment]
Thank you for respond, Beee4life.
Probably there are one thing is missed, it is possible to select to show just a country in the options, but this variant is not helpful if data is not saving after all.

It will be much better to use one plugin for both to select city or just a country, because final case to have ability to select location. In some cases like in user sign up you need just a country select.

Thank you for such plugin.

**Comment by Beee4life** [comment]
Oh snap, i forgot about that option :)

I will try to look if I can find some time to look into it.... no promises yet...

**Comment by Beee4life** [comment]
I found the issue, it's merely a typo.  You can fix it (temporarily) by changing all instances of $fields to $field in [this](https://github.com/Beee4life/acf-city-selector/blob/master/fields/acf-city-selector-v5.php#L333) function.

I'll release an update later tonight.

**Comment by Beee4life** [comment]
Should be fixed now in [this release](https://github.com/Beee4life/acf-city-selector/releases/tag/0.22.2).

**Comment by Akots** [comment]
Thanks @Beee4life
