### ISSUE TITLE
Other counties?

### ISSUE THREAD

**Issue by evandiamond** [Beee4life/acf-city-selector#57]
Hi there, I love your plugin, but was curious if you're looking into expanding the country set. The countries you support are great, but obviously missing a ton.
Also, would you consider offering a multi-pack that contains all the cities for a savings instead of purchasing all separately? Or even a subscription where you pay and get all future updates?

**Comment by Beee4life** [comment]
I have been considering both options, I just lack time since i have other plugins/projects as well..

**Comment by Akots** [comment]
+1 for pack with all countries

**Comment by evandiamond** [comment]
@Beee4life Gotta make that $

One more follow up. How do updates work with these packs? Are they automatic?

**Comment by Beee4life** [comment]
> @Beee4life Gotta make that $
hahaha, nice thought but not why I wrote this plugin :)

> @Beee4life One more follow up. How do updates work with these packs? Are they automatic?
Not quite sure what you mean ? A pack is a static csv file with cities. Some are already available.
IF for some reason I would update a country pack, then you would need to re-import it.

**Comment by Akots** [comment]
@Beee4life is it possible to get all countries pack?

**Comment by Beee4life** [comment]
Will take time to compile.... it's in the planning but very time consuming.

**Comment by Akots** [comment]
We need this on the project and would like to buy pro version with all countries, also for support this plugin. 
Please write what time it can take and the price.

**Comment by Beee4life** [comment]
@Akots I have expanded the available country packages. Are there any countries you are looking for specifically ?

**Comment by Beee4life** [comment]
Oh you can find the available countries [here](https://acfcs.berryplasman.com/get-countries/).

**Comment by Akots** [comment]
@Beee4life thank you for fixes and updates. 

As for countries pack we need all countries in one pack, just specific countries is not enough.

**Comment by Beee4life** [comment]
I have expanded the available countries again.

I also added a 'World' package which gives access to all currently available countries + any to be added countries. That might be interesting for you, but this is to be downloaded (for now) as indiv. files... but that's only about 20 downloads.

**Comment by Beee4life** [comment]
@evandiamond sorry forgot to tag you just in case ;)
