### ISSUE TITLE
Does not work. Upon Activation It Breaks the execution of wordpress.

### ISSUE THREAD

**Issue by shwetdalal** [Beee4life/acf-city-selector#60]
When activating plugin it throws error.
Had to remove plugin from code to remove the wordpress error.

After debugging found this issue.
![image](https://user-images.githubusercontent.com/37861265/92417172-80f5ff00-f17e-11ea-9928-24824e087697.png)

**Comment by Beee4life** [comment]
This sounds like your PHP version is too low.... What version do you use ?

**Comment by shwetdalal** [comment]
My php version is 5.6
And do you have provision for indian city states?

**Comment by Beee4life** [comment]
Wordpress requires a higher version if I'm not mistaken.

Line 22 of the file you mentioned reads:
```
return $a[ 'country_name' ] <=> $b[ 'country_name' ];
```
`<=>` is a so called spaceship operator. This is only available from PHP version 7 and up, see [here](https://www.tutorialspoint.com/php7/php7_spaceship_operator.htm).

Indian cities are not yet planned, I am sorry, focusing on Europe first.

**Comment by Beee4life** [comment]
So the solution is, (let your hoster) upgrade PHP.

**Comment by Beee4life** [comment]
I will add the PHP requirement to the php file in next version.

**Comment by Beee4life** [comment]
FYI: Info on php version for WP
https://wpastra.com/changing-wordpress-php-version/
