### ISSUE TITLE
Feature request: work with JetSmartFilters and JetEngine

### ISSUE THREAD

**Issue by miaosun** [Beee4life/acf-city-selector#63]
Hi @Beee4life , 

I have managed to install the plugin and imported the cities of Portugal in the database, added a custom field for my JetEngine custom post type, everything worked smoothly except the minor issues I reported in #62 .

However, I am not able to find a way to use JetEngine Dynamic Fields to get the values of city/state/country, and can't use JetSmartFilters to filter my listings with the different cities. 

Is it in your radar to make such enhancement in future, or is it too much to ask? 
In my option, these are very useful features which can benefit a lot of users. 

Looking forward to your feedback, regards!

**Comment by Beee4life** [comment]
> Is it in your radar to make such enhancement in future

No.

**Comment by Beee4life** [comment]
I just googled the plugins and it's a definite No. This plugin is an extension for ACF, not for Jetengine, which seems to be an ACF 'competitor', so not gonna happen.

**Comment by miaosun** [comment]
Thank you for looking into it.
Just to clarify, despite being 'competitors', their features seem to be compatible, at least all the standard ACF fields can be used with JetEngine and JetSmartFilters.
Anyway, I respect your decision, I'll try to find other solutions then. Regards!

**Comment by Beee4life** [comment]
I understand, but the name is ACF city selector. Even though the features might seem similar, that doesn't mean the code is. I expect a whole lot of issues, which is just not worth it, imo.
