### ISSUE TITLE
Suggestion: option to set a default country

### ISSUE THREAD

**Issue by gavinhewitt** [Beee4life/acf-city-selector#7]
Hey,

Great plugin, just what I needed! Got a suggestion though:

It would be nice to be able to set a default country so you only need to set the state/province and city. 

Verder goed bezig! ;-)

**Comment by Beee4life** [comment]
Might be a good addition... will look into it...

I hope to push everything to master somewhere early this week.

**Comment by Beee4life** [comment]
BTW how did you find it ? Didn't really promote it yet...

**Comment by gavinhewitt** [comment]
Here: https://support.advancedcustomfields.com/forums/topic/acf-countrycitystate-field/

**Comment by Beee4life** [comment]
All issues I mentioned there are fixed (afaik).

**Comment by gavinhewitt** [comment]
Somewhat unrelated question (I'm pretty new to this ACF thing, hope you can help):

I need to display an overview of all provinces (with total post count) and include a list of all cities that have posts attached (also with count, see image). How would you go about this with ACF fields?

![image](https://user-images.githubusercontent.com/1969103/32148654-a28a5230-bcfa-11e7-9045-c07d0169b8f8.png)

**Comment by Beee4life** [comment]
This is a rough idea....

    $post_args            = array(
        'post_type'      => 'post_type',
        'posts_per_page' => 999,
        'meta_query'     => array(
            array(
                'key'     => 'sd_city_selector',
                'compare' => 'EXISTS',
            ),
        ),
    );
    
    $posts_with_city_info = get_posts( $post_args );
    if ( false != $posts_with_city_info ) {
        $states_array = false;
        $city_array   = false;
        $cities_array = false;
        $city_info    = false;
        foreach ( $posts_with_city_info as $post ) {
            $field_value    = get_field( 'sd_city_selector', $post->ID );
            $city_info[]    = $field_value;
            $states_array[] = $field_value[ 'stateName' ];
        }
        if ( $states_array ) {
            $no_double_states = array_unique( $states_array );
            foreach ( $no_double_states as $state ) {
                echo $state;
                // get all array keys from $city_info where stateName == $state
                // count unique values
            }
        }
    }

I added comments where you still need to do some work, but i've been working too long today already :)

**Comment by gavinhewitt** [comment]
Ja top, hier kan ik wel iets mee.

Thanks!

**Comment by Beee4life** [comment]
Please post the result (if you found one), so someone else can also use it in case of need.

**Comment by Beee4life** [comment]
@gavinhewitt v0.1 has been released (and it has some minor fixes)

**Comment by SmallBizon** [comment]
Thank you guys, for your ideas. I finished your code. May be not best, but works for me.

`
$post_args            = array(
    'post_type'      => 'clinic',
    'posts_per_page' => 999,
    'meta_query'     => array(
        array(
            'key'     => 'sd_city_selector',
            'compare' => 'EXISTS',
        ),
    ),
);
$posts_with_city_info = get_posts( $post_args );

if ( false != $posts_with_city_info ) {
    $states_array = false;
    $city_info    = false;
    foreach ( $posts_with_city_info as $post ) {
        $field_value    = get_field( 'sd_city_selector', $post->ID );
        $city_info[]    = $field_value;
        $cities_array[] = $field_value[ 'cityName' ];
        $states_array[] = $field_value[ 'stateName' ];
    }
    
    $clinics_in_city_counter = array_count_values($cities_array);
    $clinics_in_state_counter = array_count_values($states_array);

    if ( $states_array ) {

        $no_double_states = array_unique( $states_array );
        foreach ( $no_double_states as $state ) {
          echo "<h3>" . $state . "</h3>";     
          echo $clinics_in_state_counter[$state]." клиник<br />";
          foreach ( $city_info as $address_arr){
                    
                    if ($address_arr['stateName']==$state){
                        $cities_of_state[]=$address_arr['cityName'];
                    } 
                }
        $no_double_cities = array_unique( $cities_of_state );

       echo "<ul>";
       foreach ($no_double_cities as $city) {
            echo "<li>" . $city . " " . $clinics_in_city_counter[$city]."</li>";
        }
        echo "</ul>";
        $cities_of_state=array();
        $no_double_cities=array();
        }
    }
}
`

**Comment by Beee4life** [comment]
Thank you for this, I will try to take a look at it when i have some time, but very busy this month.

**Comment by Beee4life** [comment]
This request has been outstanding for more than 2 years, but I can finally say this is now incorporated in the plugin. You can now set a default country, from the countries you have in your database.

So closing this topic now (finally) :)
