### ISSUE TITLE
Filter results / data

### ISSUE THREAD

**Issue by andreslopez93** [Beee4life/acf-city-selector#72]
Hello, first of all very good work!

My query is how to store country / state / city fields as metadata to be able to filter later?
I am using Search & Filter, and it does not detect the waterfall fields.

https://www.bobz.co/dynamically-populate-select-fields-choice-in-advanced-custom-fields

I'm following this thread to be able to auto-fill cascading fields, but I'm done with your plugin, which is fantastic.
Might you help me? or tell me how to do the exposed turorial?

Thanks!

**Comment by Beee4life** [comment]
@andreslopez93 I am not quite sure what you mean... I have no experience with the plugin Search & Filter (assuming it is another plugin.

I would not use the info from the link you provided, but use ACF's own documentation for `[acf/prepare_field](https://www.advancedcustomfields.com/resources/acf-prepare_field/)` which you can combine with the ACFCS function `[acfcs_get_cities()](http://acf-city-selector.com/function/acfcs_get_cities/)`.

```
function acfcs_load_cities( $field ) {
    
    $field['choices'] = array();

    // get cities
    $cities = acfcs_get_cities( $country_code );    
    
    // loop through array and add to field 'choices'
    if( is_array($cities) ) {
        
        foreach( $cities as $city ) {            
            $field['choices'][ $city[ 'city_name' ] ] = $city[ 'city_name' ];            
        }
        
    }
    
    return $field;
    
}
add_filter('acf/prepare_field/key=field_123abcf', 'acfcs_load_cities');
```

Is this what you mean ?

**Comment by andreslopez93** [comment]
If it looks like, I am needing to build a multi level 2 or 3 cascaded data filters with ACF.
I'm using your plugin but I can't detect the stored fields to be able to filter with this plugin (serach and filter), it needs each level to be separate and not an array.

It would be optimal if your plugin was not only limited to country / city, but also to be multilevel, let me explain?

**Comment by Beee4life** [comment]
I think I understand what you mean... If I'm correct, I already built something like this. See this screenshot.

![Screenshot 2019-04-28 at 12 13 42](https://user-images.githubusercontent.com/4508731/101088473-12291600-35b4-11eb-8eea-70f51ab2aaaf.png)

So a conditionally dropdown based on country/state ?

**Comment by andreslopez93** [comment]
Yes, it seems to be this.  what I am needing is to be able to filter in cascade example "car brands" -> "car models" -> "versions"

The date is imput to options page with ACF and 
Each level must be a field, so that when you save the post you can filter later.

**Comment by Beee4life** [comment]
I am sorry, I don't quite understand what you mean... what has the date to do with it ?

The cities don't have meta fields. You can only generate them dynamically as far as I understand correctly what you want to do.

**Comment by andreslopez93** [comment]
Perdon, misspelled date for data.
what I need is to be able to do this -->  https://bdwm.be/how-to-create-dynamically-populated-cascading-dropdown-lists-for-contact-form-7/
the same, but with ACF. each level must be a field so then I can detect and filter it.

It is very similar to what you developed, but it would be optimal to be able to implement it..

![image](https://user-images.githubusercontent.com/66543464/101093099-0ed46100-3599-11eb-8b3f-609060c55868.png)

**Comment by Beee4life** [comment]
My plugin is specifically meant for cities and not for cars.

If you want to use it, feel free to code something custom but non-cities are outside of the scope of my support.
