### ISSUE TITLE
Reduce long loading time of cities and state

### ISSUE THREAD

**Issue by Akots** [Beee4life/acf-city-selector#78]
We encountered a very long waiting time, after selecting a country the interface freezes.
It looks that it makes second request for load all cities and in cases like India it is about 2.7s.

![image](https://user-images.githubusercontent.com/286709/102474074-df295c80-4060-11eb-8210-4907f0e3de47.png)

Is there are reason to pre load all cities right after load states?
Also is there are way to optimize server time? Currently execution of get_states_call time is about 450-600ms, so for users is start to be not good experience.

Thank you for support

**Comment by Beee4life** [comment]
This exact point (sometimes slow response) is mentioned in the plugin's disclaimer.

The states and cities need to be loaded once to create the transient, which speeds up the process.
You could manually call the transient function when loading the field ? So it's created already when it's needed.

> Is there are reason to pre load all cities right after load states?
Cities are loaded after country change, not after load states s not sure what you mean.

**Comment by Akots** [comment]
@Beee4life the point is to not trigger load of cities after select country if state is not selected, now it tries to get all cities within country. I am not so good understand WP logic behind this, but this can be problem for users, the UI is stuck within big countries.

**Comment by Beee4life** [comment]
That's why I suggested a preload. I changed this on purpose a few versions ago... to try and minimize the loading time.

**Comment by Beee4life** [comment]
I'm not saying that was the ideal/perfect decision... because state is still obligated to enter (if you don't choose 'country + city'), so I will look into it, if I have some time.

**Comment by Akots** [comment]
Ok, I understand the logic behind this it make sense, thanks for looking on this.

**Comment by Beee4life** [comment]
I am focusing right now on cleaning code to get the plugin into the official WP repo so that has priority.

**Comment by Beee4life** [comment]
I have removed the loading of cities on change country, see [here](https://github.com/Beee4life/acf-city-selector/blob/master/assets/js/city-selector.js#L68-L69). Now only states are loaded.

I will optimize it a bit more later on.

**Comment by Akots** [comment]
Thank you, it works better now.

**Comment by Beee4life** [comment]
Good, then I'll close this topic for now.
