### ISSUE TITLE
Incorrect NL provincecodes

### ISSUE THREAD

**Issue by gavinhewitt** [Beee4life/acf-city-selector#8]
Currently Zeeland and and Gelderland are defined as ZL and GL, but should be ZE and GE.

See https://en.wikipedia.org/wiki/ISO_3166-2:NL#Current_codes

**Comment by Beee4life** [comment]
Gotcha.... will change this before the merge to master.

**Comment by Beee4life** [comment]
Fixed: https://github.com/Beee4life/acf-city-selector/pull/9
