### ISSUE TITLE
Working with taxonomies

### ISSUE THREAD

**Issue by leightona** [Beee4life/acf-city-selector#85]
Thanks for creating this, there’s surprising not a lot out there. 
When you say works “on taxonomy terms” I’m not clear how to implement this and make a connection with my custom taxonomy?
As far as I can see I can only select one Field Type - either City Selector or Taxonomy and I can’t see a filter to connect taxonomy terms. 
Ideally I would like to store as hierarchical taxonomy country>state>city in order to simplify use in other functions like 3rd part search plugins.
Any suggestions would be appreciated.

**Comment by Beee4life** [comment]
I think you misunderstand what it's about, in reg. to taxonomy terms.

With ACF Pro you can add fields to taxonomy terms. If you know how to do that, you can also add a new field with the city selector.

The hierarchy you speak of is not something which is related to this plugin.

**Comment by leightona** [comment]
So do you mean using a snippet to sync City Selector fields with taxonomy terms?
E.g. using wp_get_object_terms() and wp_set_object_terms() and update_field()?

At present I have only used the Taxonomy field type’s load and save GUI to achieve taxonomy syncing.

**Comment by Beee4life** [comment]
> So do you mean using a snippet to sync City Selector fields with taxonomy terms? E.g. using wp_get_object_terms() and wp_set_object_terms() and update_field()? At present I have only used the Taxonomy field type’s load and save GUI to achieve taxonomy syncing.

No, you use get_field. Explained [here](https://www.advancedcustomfields.com/resources/adding-fields-taxonomy-term/).
