### ISSUE TITLE
PayPal link broken - get countries

### ISSUE THREAD

**Issue by leightona** [Beee4life/acf-city-selector#86]
FYI your PayPal link to purchase countries is coming up with error “We're sorry, things don't appear to be working right now. Please try again later.” So you can’t purchase country packages. 
using this page https://acf-city-selector.com/get-countries/

**Comment by Beee4life** [comment]
Thanks for the heads up. I will look into it asap. I can help you manually if you're in a rush.

**Comment by leightona** [comment]
No problem. Have added a dataset manually but will make a donation to contribute.

**Comment by Beee4life** [comment]
I think the problem is now solved. For some reason all my PayPal credentials were gone. 

Would it be possible to check/verify ?
