### ISSUE TITLE
City not showing after importing from CSV

### ISSUE THREAD

**Issue by ekadigitalmakers** [Beee4life/acf-city-selector#91]
Hello guys,

a long time ago we did a huge import of cities (like 100 entries or so) in a project and is working normally. Now the unhappy part is when we try to import a new city and all the process is ok but unfortunately it is not showing in ACF selectors in our post as others cities/countries do.
 
The new city is showing in acf-city-selector dashboard and it is correctly added to DB (sounds obvious) but we dont know why is not showing in the selectors. Not sure if it is an ACF or ACF-City-Selector issue.

Any clue on how to fix this?

**Comment by Beee4life** [comment]
My first guess is you need to delete the transients, see the checkbox on settings page.

**Comment by Beee4life** [comment]
Closed due to non-response.
