### ISSUE TITLE
US Countries not working.

### ISSUE THREAD

**Issue by RobbySwinden** [Beee4life/acf-city-selector#96]
The us.csv file has the errors '**There are too few columns on all lines. Since your file is not accurate anymore, the file is deleted.**

Regards,

**Comment by Beee4life** [comment]
Sorry to hear that, I will look into it asap.

**Comment by Beee4life** [comment]
I have updated the US file. It was a comma separated file, which indeed gave some errors. 

I replaced it with a semi-colon delimited file which works fine for me. 

Just re-download the file and you should be good.

**Comment by RobbySwinden** [comment]
This works just fine now, thank you 🥇
