### ISSUE TITLE
Add Armenia Country

### ISSUE THREAD

**Issue by airarm** [Beee4life/acf-city-selector#97]
Hi @Beee4life 

I create Armenia country import csv https://gist.github.com/airarm/11ed9183a501ea6a011b9c180999b65a

You can add Armenia country to your supported countries list

Thank you for great plugin!

**Comment by Beee4life** [comment]
I will check it out, @airarm appreciated.

**Comment by Beee4life** [comment]
I looked at it and it looks good. I added it to the free countries list on [the website](https://acf-city-selector.com/get-countries/). Thanks.

**Comment by airarm** [comment]
@Beee4life Thanks you too!
